name: Pendulum
version: 'SNAPSHOT-26w31ae'
main: org.delta.pendulum
api-version: '1.21'
authors: [ Erick Segura ]
description: Plugin para el servidor Pendulum
commands:
  pendulum:
    description: Comando principal del plugin de Pendulum.
    aliases: pdl
permissions:
  pendulum.canjear:
    description: Permite canjear códigos de easter egg con /pdl canjear.
    default: true
